### ISSUE TITLE
"Have Questions about Hypha?" User Support link

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#11]
Zulip, GitHub, we.hypha.app are all places where folks can ask questions (e.g. if documentation for that question cannot be found by browsing docs info)

@emlini will add info on this to the QuickStart page

**Comment by frjo** [comment]
Hypha Community first stop I believe is https://we.hypha.app/.

Zulip is good for quick chats and GitHub for when there is specific issues to work on.

**Comment by fourthletter** [comment]
we.hypha.app currently has this available to current and new end-users

![image](https://user-images.githubusercontent.com/20019656/188668125-47a3c91b-b5b6-4a00-b91d-a97e083552f5.png)
