### ISSUE TITLE
Delete old wiki pages

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha-docs#14]
I have synced up some changes to the developer environment setups and update all gitHub links to HyphaApp repo.

If you have moved everything else from the wiki to the docs here I think we should delete the wiki pages.

**Comment by ei8fdb** [comment]
@frjo I've marked them as archived and pointed them to the new docs pages.

If you want I can delete the pages. I've no preference.

**Comment by frjo** [comment]
After the information in them have been moved to the documentation I think we can delete them.

**Comment by emlini** [comment]
Are we talking about [these wiki pages](https://github.com/HyphaApp/hypha/wiki)?

**Comment by frjo** [comment]
@emlini Yes, the ones that have been moved to the documentation.

**Comment by emlini** [comment]
This is done right?  Can be closed?

**Comment by ei8fdb** [comment]
I've not been following this for a while. If the important wiki pages have been replicated on documentation then they can be deleted.

**Comment by Erioldoesdesign** [comment]
I'll take the issue to check over whether this has been done accurately before closing
