### ISSUE TITLE
"in-progress" notification & contact

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#20]
As I create some of the user documentation pages, I'm realizing I'd like to be able to put a **notification that the page is a work in progress**, that I am open to feedback/change suggestions, and provide readers with the steps for submitting any feedback/change suggestions.  This will help be get *some* documentation published more quickly because I won't feel the need to sit on it while I double and triple-check that what I've written is totally accurate, but will also alert the reader that the information may be in flux or sometimes inaccurate (hopefully not too badly).

Two main questions:

1. Is this done?  If so, is there preferred phrasing (i.e. "under construction", "in progress", etc), formatting (font size, type set), & placement (top/bottom of page) for this kind of announcement? Do we want an image/banner to indicate page is under construction? 
2. How should I direct folks to post updates/questions?  My preference is to direct them to post an issue on Github (if they have an account), and if they don't do Github, then post on we.hypha.app.  But maybe I should put the non-tech option first, then say "or if you have a Github account" you can create a new "issue" [here](https://github.com/HyphaApp/hypha-docs/issues).  I'm trying to strike a balance between making sure folks, including non-tech-savvy folks, can (easily) point out errors/make suggestions for documentation, but I don't want to become a bottleneck for the process.  

@danblah @maxpearl @ei8fdb @frjo asking for your input. 

**Related but slightly tangential note**: writing out (2) is making me think we need "How to contribute" pages in the documentation, possibly for Hypha main and Hypha documentation.  If folks agree I'll create a ticket for both. Still would like input on what the brief "in-progress" note on individual documentation pages should say, if we think there should be one.

**Comment by frjo** [comment]
Adding an "In progress" notice sounds good to me.

If you want to style it GitBook has this https://docs.gitbook.com/editing-content/markdown#hints-and-callouts. The "info" hint might work well for this.

I think GitHub issues will work well in practice. But giving other options is good. It will realistically not be random people who wants to improve the docs, it will be people from organisations we already work with.

**Comment by emlini** [comment]
Both "In-progress" and "how to make suggestions/contributions" banners have been added to all Doc pages that are still in development (at the top and bottom, respectively)
