### ISSUE TITLE
Document *.py configuration files

### ISSUE THREAD

**Issue by maxpearl** [HyphaApp/hypha-docs#21]
[hypha/settings](https://github.com/HyphaApp/hypha/tree/c3c2f95f4727e4633efbb4cc258321d99e13f50e/hypha/settings) have settings files that could use documentation: This includes  [base.py](https://github.com/HyphaApp/hypha/blob/c3c2f95f4727e4633efbb4cc258321d99e13f50e/hypha/settings/base.py), [dev.py](https://github.com/HyphaApp/hypha/blob/c3c2f95f4727e4633efbb4cc258321d99e13f50e/hypha/settings/dev.py), [production.py](https://github.com/HyphaApp/hypha/blob/c3c2f95f4727e4633efbb4cc258321d99e13f50e/hypha/settings/production.py), and other files.

1) Document what each file does.
2) Document what each setting does.
3) Indicate the configurability of each setting.

I think a new folder in hypha-docs, called "configuration" with a page for each file is probably the way to go, as it opens up a place to put other admin configurations that are in the wagtail and hypha interface.

**Comment by frjo** [comment]
* base.py – Base settings file. Other settings file start by loading this in.
* dev.py – This is settings for development work.
* example.py – Example settings, not loaded anywhere. (This file should be expanded to cover more settings.)
* local.py.example – Copy and rename to "local.py" and it will be loaded by both production and dev settings. Main use is to allow developers an easy way to set and test settings. Can also be used in production but environment variables are the preferred and more secure way.
* production.py – This is settings for production use.
* test.py – This is setting for when running tests.

**Comment by frjo** [comment]
I believe this is a complete list of all settings in use by Hypha. Most are Django and Wagtail settings. 

ALLOWED_HOSTS
ANYMAIL
API_BASE_URL
APP_NAME
AUTH_PASSWORD_VALIDATORS
AUTH_USER_MODEL
AUTHENTICATION_BACKENDS
AWS_ACCESS_KEY_ID
AWS_DEFAULT_ACL
AWS_MIGRATION_ACCESS_KEY_ID
AWS_MIGRATION_BUCKET_NAME
AWS_MIGRATION_SECRET_ACCESS_KEY
AWS_PRIVATE_BUCKET_NAME
AWS_PRIVATE_CUSTOM_DOMAIN
AWS_PUBLIC_BUCKET_NAME
AWS_PUBLIC_CUSTOM_DOMAIN
AWS_QUERYSTRING_EXPIRE
AWS_S3_CUSTOM_DOMAIN
AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME
BASE_DIR
BASE_URL
BASIC_AUTH_LOGIN
BASIC_AUTH_PASSWORD
BASIC_AUTH_WHITELISTED_HTTP_HOSTS
BASIC_AUTH_WHITELISTED_IP_NETWORKS
BLEACH_ALLOWED_ATTRIBUTES
BLEACH_ALLOWED_STYLES
BLEACH_ALLOWED_TAGS
BLEACH_STRIP_COMMENTS
BLEACH_STRIP_TAGS
CACHE_CONTROL_MAX_AGE
CACHE_CONTROL_S_MAXAGE
CACHES
CELERY_BROKER_URL
CELERY_TASK_ALWAYS_EAGER
COUNTRIES_OVERRIDE
CSRF_COOKIE_SAMESITE
CSRF_COOKIE_SECURE
CURRENCY_SYMBOL
DATABASE_ROUTERS
DATABASES
DATE_FORMAT
DATETIME_FORMAT
DATETIME_INPUT_FORMATS
DEBUG
DEBUG_TOOLBAR_CONFIG
DEBUGTOOLBAR
DEFAULT_FILE_STORAGE
DEFAULT_PER_PAGE
EMAIL_BACKEND
EMAIL_FILE_PATH
EMAIL_HOST
EMAIL_HOST_PASSWORD
EMAIL_HOST_USER
EMAIL_PORT
EMAIL_SUBJECT_PREFIX
EMAIL_USE_SSL
EMAIL_USE_TLS
ENABLE_STYLEGUIDE
ENABLE_WEBPACK_BUNDLES
ESI_ENABLED
FEED_CACHE_TIMEOUT
FILE_ACCEPT_ATTR_VALUE
FILE_ALLOWED_EXTENSIONS
FILE_FORM_CACHE
FILE_FORM_TEMP_STORAGE
FILE_FORM_UPLOAD_DIR
FORM_RENDERER
HIJACK_DECORATOR
HIJACK_LOGIN_REDIRECT_URL
HIJACK_LOGOUT_REDIRECT_URL
INSTALLED_APPS
INTERNAL_IPS
LANGUAGE_CODE
LOCAL_FILE_EMAIL
LOCAL_FILE_LOGGING
LOCALE_PATHS
LOGGING
LOGIN_REDIRECT_URL
LOGIN_URL
MAILCHIMP_API_KEY
MAILCHIMP_LIST_ID
MATOMO_SITEID
MATOMO_URL
MEDIA_ROOT
MEDIA_URL
MESSAGE_LEVEL
MIDDLEWARE
ORG_EMAIL
ORG_GUIDE_URL
ORG_LONG_NAME
ORG_SHORT_NAME
PASSWORD_HASHERS
PASSWORD_REQUIRED_TEMPLATE
PASSWORD_RESET_TIMEOUT_DAYS
PGCRYPTO_DEFAULT_KEY
PRIVATE_FILE_STORAGE
PROJECT_DIR
PROJECTS_AUTO_CREATE
PROJECTS_ENABLED
REFERRER_POLICY
REST_FRAMEWORK
ROOT_URLCONF
SALESFORCE_QUERY_TIMEOUT
SECRET_KEY
SECURE_BROWSER_XSS_FILTER
SECURE_CONTENT_TYPE_NOSNIFF
SECURE_HSTS_SECONDS
SECURE_PROXY_SSL_HEADER
SECURE_SSL_REDIRECT
SEND_MESSAGES
SEND_READY_FOR_REVIEW
SERVER_EMAIL
SESSION_COOKIE_SAMESITE
SESSION_COOKIE_SECURE
SHORT_DATE_FORMAT
SHORT_DATETIME_FORMAT
SLACK_DESTINATION_ROOM
SLACK_DESTINATION_ROOM_COMMENTS
SLACK_DESTINATION_URL
SLACK_TYPE_COMMENTS
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS
SOCIAL_AUTH_LOGIN_ERROR_URL
SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL
SOCIAL_AUTH_PIPELINE
SOCIAL_AUTH_URL_NAMESPACE
STAFF_EMAIL_DOMAINS
STATIC_ROOT
STATIC_URL
STATICFILES_DIRS
STATICFILES_STORAGE
TEMPLATES
TIME_ZONE
TRANSITION_AFTER_REVIEWS
USE_I18N
USE_L10N
USE_TZ
WAGTAIL_CACHE
WAGTAIL_CACHE_BACKEND
WAGTAIL_CACHE_TIMEOUT
WAGTAIL_PASSWORD_MANAGEMENT_ENABLED
WAGTAIL_SITE_NAME
WAGTAIL_USER_CREATION_FORM
WAGTAIL_USER_CUSTOM_FIELDS
WAGTAIL_USER_EDIT_FORM
WAGTAILADMIN_RICH_TEXT_EDITORS
WAGTAILEMBEDS_RESPONSIVE_HTML
WAGTAILFRONTENDCACHE
WAGTAILIMAGES_FEATURE_DETECTION_ENABLED
WAGTAILIMAGES_IMAGE_MODEL
WAGTAILSEARCH_BACKENDS
WAGTAILUSERS_PASSWORD_ENABLED
WAGTAILUSERS_PASSWORD_REQUIRED
WEBPACK_LOADER
WSGI_APPLICATION

**Comment by frjo** [comment]
Here follow a subset of setting that are Hypha specific:

API_BASE_URL
CURRENCY_SYMBOL
DEFAULT_FILE_STORAGE
MATOMO_SITEID
MATOMO_URL
ORG_EMAIL
ORG_GUIDE_URL
ORG_LONG_NAME
ORG_SHORT_NAME
PRIVATE_FILE_STORAGE
PROJECTS_AUTO_CREATE
PROJECTS_ENABLED
SEND_MESSAGES
SEND_READY_FOR_REVIEW
SLACK_DESTINATION_ROOM
SLACK_DESTINATION_ROOM_COMMENTS
SLACK_DESTINATION_URL
SLACK_TYPE_COMMENTS
STAFF_EMAIL_DOMAINS
TRANSITION_AFTER_REVIEWS

**Comment by frjo** [comment]
In release https://github.com/HyphaApp/hypha/releases/tag/v1.69.0 we added a new Hypha specific setting

SUBMISSIONS_TABLE_EXCLUDED_FIELDS

Exclude Filters/columns from submission tables. Possible values are: fund, round, status, lead, reviewers, screening_statuses, category_options, meta_terms

If set directly it should be a list, if added via environment variables, make it a comma separated string. It will be converted in to a list.

**Comment by Erioldoesdesign** [comment]
Does this need an 'explainer page' in GitBooks(docs.hypha.app) for non-technical and technical users? or is it already there?

If so I can create a blank holding page there and also add some labels here to track what status this task is in.

Associated we.hypha forum post here: https://we.hypha.app/t/documenting-the-hypha-customisation-options/153

**Comment by frjo** [comment]
@Erioldoesdesign This issue is about adding this to docs.hypha.app, I think that would be helpful for implementers.

**Comment by maxpearl** [comment]
I'm working on adding this to the docs. New directory called "configuration" with a readme that explains each settings file, then one page each for each settings file explaining the settings.

**Comment by maxpearl** [comment]
@frjo Just committed a bunch of docs on the configuration files. (https://github.com/HyphaApp/hypha-docs/commit/411b7b9edccb0f439b55a2b7f3ec4db10b7c73ea) Please let me know if there is important stuff I missed.
