### ISSUE TITLE
Make "How to create Form/Fund/Round" page

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#24]
Title: Something like "Setting up your first submission cycle"? - think about terminology that most makes sense to adopters

Include workflow graphic, once it is completed.

**Comment by frjo** [comment]
I think screencasts can be useful here as well.

**Comment by fourthletter** [comment]
Currently available here: https://github.com/HyphaApp/hypha-docs/tree/main/docs/staff/set-up-your-first-application and here: https://docs.hypha.app/staff/set-up-your-first-application/
