### ISSUE TITLE
[Meta] Accessibility ‘audit’ for hypha.app

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha-docs#26]
Hypha.app has not prioritised accessibility across the tool and associated docs and tools for time and resources reasons.

Various organisations offer 'accessibility audits' as part of their service but until that is prioritised in the general Hypha budget we're inviting other contributors to work on accessibility audit tasks for Hypha.app.

This issues comment section can gather suggestions and resources on how to perform individual issue tasks around accessibility audits.

---

_This is a [Meta] level issue otherwise known as an 'Epic' where this issue describes a larger project and collects smaller issues within it._

**Comment by Erioldoesdesign** [comment]
The task issues within this Meta/Epic will begin with using https://www.a11yproject.com/checklist/ as a guide for tasks.

**Comment by fourthletter** [comment]
An accessibility audit was completed 2019 by Accessibility Lab

Development completed: https://github.com/HyphaApp/hypha/issues/2895 & and technical documentation will be drafted  by February 2023 https://github.com/HyphaApp/hypha/issues/3083
