### ISSUE TITLE
[Meta] Usability tests with impaired/disabled users

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha-docs#27]
As part of the documentation teams ongoing work to increase accessibility knowledge around Hypha.app we would like some general usability tests to occur with impaired users.

Tasks in this Meta project include:

- Writing a user-testing script for Hypha.app for various different impairments and disabilities including combinations of impairments and disabilities.
- Recruiting impaired and disabled people to do the user tests.

**Comment by fourthletter** [comment]
Accessibility Lab completed an audit in 2019; we will pursue a new engagement with them again in 2023
