### ISSUE TITLE
Make doc page on Creating Accounts

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#30]
Pursuant to [conversation on Zulip](https://chat.hypha.app/#narrow/stream/1-general/topic/Combining.20applicant.20accounts/near/4263), specifically comment from Allan Stanley (working with Digital Freedom Fund)

`We found the account creating step a bit confusing. Perhaps looking at providing different ways for doing so might help. for eg:
 - invites only
 - open registration
 - as it is right now, depending on the email used for the submission
Right now we deal with this editorially; in the application guidelines and in the help text for the email field.`

## **We need to create TWO pages:**
1. A "Create new user" page under "Staff"  - this exists, but needs to be fleshed out (e.g. Wagtail screenshots and more detail added)
   - *Note: I believe the "invites only" instance is accounted for in the directions on this page--i.e., if an organization wants to invite applicants to submit, a Staff member would presumably create the invitee's account and assign them the role "Applicant"*
2. A "How to create an account" page under "Applicant"
   - *Note: This page may need to include multiple pieces of information.  Accounts are automatically generated when someone applies for a grant, but it seems like Digital Freedom Fund might also allow users to create accounts without specifically applying for grants* (@frjo is this a feature of Hypha core?)

**Comment by emlini** [comment]
1.  "Create a new user" page exists [here](https://docs.hypha.app/staff/createusers) now, under "Staff" section.

2. After conversation with folks (e.g. @Erioldoesdesign, @ei8fdb, & @frjo), it seems like it will *not* be an option in Hypha core (OSS?) for applicants to be able to create accounts separately from applying for funds.

If my perception of #2 is correct, this issue can be closed.

**Comment by Erioldoesdesign** [comment]
re. 2. I think any person that works for the funder that deploys hypha (OTF, Reset etc.) can create a user in Hypha and send an email to them to 'activate' their account but from an applicant perspective, they 'create' an account when they apply for a fund.

**Comment by Erioldoesdesign** [comment]
So yes I think this can be closed :)
