### ISSUE TITLE
Make Hypha Workflows documentation page

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#31]
From Maintainer's meeting 14th December (notes [here](https://we.hypha.app/t/maintainer-s-call-14th-december-2021/221))

### **Goal**:
 - Document the possible workflows in Hypha for program managers (Folks with "Staff" and "Administrator" roles)

### **Where does it belong?**
 - Probably under Staff or Administrators section

### **What should it contain?**
**Documentation that would be useful (from @fourthletter (Di) on behalf of OTF):**	
 	- What are the workflows? (we know that there are currently 4 hard-coded workflows in Hypha core, code for which is  [here](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/workflow.py))
	- How do you select your workflow?
	- What does workflow mean for how an application is routed? (Right now I believe this routing is not automatic, but that needs confirmation)
	- *screenshots would be great*

**Comment by emlini** [comment]
@Erioldoesdesign has taken screenshots necessary for workflow.

Where are these currently?  Can they be uploaded to "Files" repository on Gitbook for Hypha docs?

**Comment by fourthletter** [comment]
@emlini thank you for starting this GH issue. Here is an outline of OTF's guide on the workflows: https://docs.opentech.fund/otf-hypha-field-guide/build/select-a-workflow -- **please feel free to edit for Hypha Core**.

## User story
> As a funder I need select a workflow that aligns with my application process. 

## Describe the documentation you'd likely need

- [ ] As staff member I need guidance on which workflows are available in Hypha so I can select the option that works best for my fund/lab. This information would be useful to help me set up a fund/application. 

- [ ] As a _potential_ adopter/implementer I would like to know which workflows are available in Hypha so I can consider whether Hypha is an application platform that could accommodate my application process.


The Workflow defines the stages and processes that the application could undertake. Creating a new Fund or Lab requires you to select one of these workflows. 

Each workflow has a predetermined amount of stages (e.g. request, proposal), application forms, review forms, and determination forms associated with this Fund or Lab.  

Each workflow offers different statuses (e.g. External Review, Ready for Determination), and different actions (e.g Invite to proposal). 

<img width="782" alt="Screen Shot 2022-01-07 at 6 40 59 PM" src="https://user-images.githubusercontent.com/20019656/148585339-c3f82c89-04e2-4104-9ad4-ad38c0da591b.png">

<img width="780" alt="Screen Shot 2022-01-07 at 6 41 10 PM" src="https://user-images.githubusercontent.com/20019656/148585346-978a2e24-5c6a-4db0-9aa9-7c4b9bca5452.png">

<img width="774" alt="Screen Shot 2022-01-07 at 6 41 19 PM" src="https://user-images.githubusercontent.com/20019656/148585350-4d80adf4-1861-44c2-9bce-346ed7b61da2.png">

<img width="775" alt="Screen Shot 2022-01-07 at 6 41 28 PM" src="https://user-images.githubusercontent.com/20019656/148585353-7380ebf6-85b2-476b-a96b-7b903124437a.png">

**Comment by Erioldoesdesign** [comment]
Here are the mocks that I made:
https://we.hypha.app/t/workflow-screenshots-mockups/229 
https://www.figma.com/file/vJwfjjVgMPgX0wPQdbB1Qu/Hypha-workflows?node-id=0:1

Don't know how much parity they have with OTF.

I'm meeting with other adopters and discussing over email what workflows they currently use and why. 
Also to get an understanding of whats missing

**Comment by fourthletter** [comment]
@emlini I forgot to give you the proposal screenshot (only in the two stage concept note & proposal workflow)

<img width="822" alt="Screen Shot 2022-01-25 at 3 31 25 PM" src="https://user-images.githubusercontent.com/20019656/150996035-9b3db206-ecf2-453a-baa3-b083a83f89e4.png">

**Comment by emlini** [comment]
Thanks!  Added it.

**Comment by fourthletter** [comment]
Completed here https://github.com/HyphaApp/hypha-docs/blob/main/docs/staff/set-up-your-first-application/select-a-workflow.md
