### ISSUE TITLE
FAQ Docs page

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#33]
From Maintainer's meeting 2/8/21 - Notes [here](https://pad.riseup.net/p/F4-omns3EXkOCyaIzAUp-keep), see the FAQs @fourthletter started after usual meeting agenda notes 

**Questions**: 
- Where does this belong (in docs organization)?
- What are the FAQs (have three, surely there are more)?
    - Where should we look for/solicit additional FAQs?
    - What is a good limit to the number of FAQs we want on this page?
- Some answers to FAQs (either existing or yet-to-be-solicited) may not be fully fleshed out, where do we look (or who do we ping) for answers?

**Comment by Erioldoesdesign** [comment]
### Frequently Asked Questions (FAQ)

**Is NEW adopter onboarding available?**

Yes, we will have a 1:1 meeting, new adopter onboarding documentation, online forum to access the Hypha community. During the 1:1 meeting we provide you with tips and guidance on how your funding mechanism could be steered through Hypha. The information on workflows, processes, documents you share with us is confidential and it is entirely up to your discretion.

Please contact [ ] if you would like to have a meeting or join this online forum

**2. How could I contribute to this open source project?**

We are humbled and grateful for any code, design, documentation, bug reports, virtual hugs, and any other forms of contributions made to Hypha.

We aim to foster design and development improvements that would benefit the entire Hypha community. For major changes that would impact Hypha’s core infrastructure and cross-projects, we encourage a public discussion to help the community become aware of the need and the problems contributors are working to solve. This public discussion can often help contributors recruit others to help do the work, as well as gather feedback.

We are interested in learning more about any challenges and feedback on how to improve the platform. Please submit your bug reports to the main repo here: [insert GitHub repo]

Adopters could also provide input into new designs, user research, etc. There are several types of contributions you can make:

Adopter contributions/user agreements

UX contributions/user agreements

Design contributions/user agreements

**3. Is there a governance structure for adopters deploying their own forks and instances?**

Instances working on their own development fork can make their own technical decisions and manage their day-to-day activities, create new repositories in their orgs, etc., with independence and autonomy. Implementers determine their own decision making processes at the instance level, and evolve their own self-governance based on the skills assembled.

**Comment by fourthletter** [comment]
other questions...

Q: Where could I find more information on deploying my own instance?
A: Please go here https://docs.hypha.app/readme-1

Q: What is Hypha's data privacy or responsibility policy?
A: Hypha is self-hosted. This means that the applications, and all associated information created is available to you and your applicants on your own systems - not handed over to a company where it can be difficult to analyze the data. The Hypha code is regularly audited and has many privacy and security features. https://www.hypha.app/

Q: What types of types of funding structure, mechanism, or workflow does Hypha support? 
A: Hypha currently supports a majority of funding types. Please see this doc [ ] or contact [] for a demo

Q: How long has Hypha been in existence? 
A: centraries 

Q: Is there a test instance I could try (di: I'm not sure if this is a FAQ)

Q: Why the name “Hypha”?
Hyphae: long, branching ecosystem enriching organisms that form interconnected networks to collectively exchange resources. Hypha aims to support its users do the same.

**Comment by emlini** [comment]
Link to current docs FAQ page: https://docs.hypha.app/frequently-asked-questions-faqs

**Comment by emlini** [comment]
@fourthletter I'm including the first three on the FAQ page.  The other three I think are covered elsewhere.   :-)

**Comment by fourthletter** [comment]
### How can I help?
The easiest way to help is to simply use Hypha. The more you use it, the more likely you will perhaps find a bug, or miss a particular feature. Tell us about it on https://we.hypha.app/, submit it as a GitHub issue or, even better, fix it yourself and submit the code. 

If you want to get involved in the development process, here's some suggestions where to start:

Documentation
Missing test cases
Report and reproduce bugs
Bug fixes
Review pull requests
Implement new features

### I've found a bug, but I don't have the skill/time/whatever to fix it.
No problem. If it's really an unfixed bug, you're perhaps the first to stumble upon it. Write a message to https://we.hypha.app/ explaining what's wrong and, ideally, providing a test case so the developers can reproduce the error.

If it's a confirmed bug, you should add a ticket to here [https://github.com/HyphaApp/hypha/issues]

### Which kind of patches are accepted into Hypha?
There is no definitive answer to this. Bug fixes and missing QA codes are of course always welcome.

### How long does it take for my patch to become part of Hypha?
There is no definitive answer to this. It depends on many things: the complexity and size of the patch, the current situation of development and the relevance of the patch.
