### ISSUE TITLE
Revise/move Deployment Docs or rename "Administrators" section?

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#36]
Deployment docs are currently under the "[Administrators](https://docs.hypha.app/administrators)" section of documentation, which per [this document](https://docs.google.com/spreadsheets/d/1xtfnPa7xklQFHrfNNIyjYxWsQe7GwkQGe_ZNXIKaB58/edit?usp=sharing) was for "_Person at funding org who is in charge of other Staff_"

Is this where we want them?  See [this post](https://we.hypha.app/t/who-are-administrator-docs-for/302) for more detailed description (& hopefully discussion)

**Comment by fourthletter** [comment]
Issue will be resolved via this github issue https://github.com/HyphaApp/hypha-docs/issues/52
