### ISSUE TITLE
Edit Community docs pg

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#37]
Answer to “How can I join” meetings question? on Commune with us docs page
  - Suggestion: funnel all requests through Introduction post - https://we.hypha.app/t/welcome-to-the-hypha-lounge/8

**Action plan**: edit Commune page to direct folks to this post plus advise "request access in your introduction post"

**Comment by emlini** [comment]
One question I have is who do we ping to get this access?  Who is actually responsible for giving the access to the Google meetings? @Erioldoesdesign do you know?

**Comment by Erioldoesdesign** [comment]
I have 'owner' status on both maintainers and adopters google meets. In the maintainer call we.hypha posts at the top it says something like @ maintainers to be added to the google meet calendar invite. SO there is a way to ask for access, it's just not very accessible/visible/obvious. You can add in my org email to the docs if it helps sign post people that want to join for now eriol@simplysecure.org

This also doesn't solve the problem of if an 'owner' of the google meet room link can't make a meeting how do folks get into the video call...this is why I do think it's worth not relying on google meet in the near to mid future, using Jitsi would reduce the reliance on non-oss tools but google does afford a level of security that an open Jitsi room doesn't

**Comment by Erioldoesdesign** [comment]
The choices on how/who to invite to maintainers calls:

1. Governance processes will further define how/who is invited and what that process includes
2. What tools we use for what reasons

**Comment by emlini** [comment]
Currently at the top of each maintainer's call agenda on we.hypha.app is the following:

"If you’d like access to the google meet room, send a message to the [@maintainers](https://we.hypha.app/groups/maintainers) group. If you’d like to be added to the calendar invite please DM [@eriol](https://we.hypha.app/u/eriol) ."

Will this phrasing work for now for the "How can I join" question on the Maintainer's call and the Adopter's call?

**Comment by Erioldoesdesign** [comment]
I think for now it solves some of the immediate problem as we develop the first iteration of governance :)

These kind of things will never be 'perfect' in that we'll never cover every potential new users needs to join and understand spaces but i feel like we have a good casual iteration process for now.

**Comment by fourthletter** [comment]
Individuals could reach out to the Hypha team via we.hypha.app or the product page https://www.hypha.app

Contact information is no longer included in documentation. Documentation will primarily focused on providing users with guidance on how to use the platform.

![image](https://user-images.githubusercontent.com/20019656/188669671-d5425ca3-f7c2-47fc-b280-c142e9bff267.png)
