### ISSUE TITLE
What to do with end-user docs

### ISSUE THREAD

**Issue by maxpearl** [HyphaApp/hypha-docs#4]
Docs are [here](https://docs.google.com/document/d/1OQpHC79yTIetXRPOSNTOM9A5Kubs-ym0I7a2d68fQDM/edit). 

Migrate to this repo intact, and edit, or use as a template/ guide to create new docs?

**Comment by emlini** [comment]
I vote for using this as a starting point to create a template (umbrella) documentation.  We can make organizational, formatting, and content edits (especially incorporating feedback from other Hypha users re: what they want to know how to do).  Then this template/umbrella documentation could be taken and edited by specific organizations for their own use.

Thoughts?
