### ISSUE TITLE
Document Hypha localization options Pt. 1

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#40]
## What to add:
Info for developers (likely working with adopters or potential adopters) who would like to contribute translations of Hypha pieces into another language (or into terminology specific to their organization) 

Last I talked with @frjo, there were two ways to do this:

**Option A:**
- Identify strings (text) to be changed in [this file](https://github.com/HyphaApp/hypha/blob/main/hypha/locale/en/LC_MESSAGES/django.po)
- Create new folder in "/locale" folder with new language (or organization) code (e.g. "en_gb" for British English, or "en_OrgName" for a specific organization's file)
- Copy above-linked file into new folder, and edit strings as you like!  

**Option B:**

- Create a translation in [Hypha's Webblate](https://hosted.weblate.org/projects/hypha/)
- I have less information about the process here, but am hopeful Weblate's documenation has more information
- _Note: [Transifex](https://www.transifex.com) was also mentioned in the [29th March Ideation Meeting](https://we.hypha.app/t/monthly-ideation-meeting-2022-march-29th/328)?   @ei8fdb or @danblah can you expand more on the difference between these two?_

## Where should it go:
Main Contributing page, under [Translation section](https://docs.hypha.app/contributors#translation]

**Comment by emlini** [comment]
Note from 4 Apr maintainer's call: don't have to use Hypha's weblate account - can set up their own, copy Hypha's .po file, and translate away!

**Comment by fourthletter** [comment]
Completed and released here: https://github.com/HyphaApp/hypha-docs/issues/43
