### ISSUE TITLE
MkDocs on Netlify for documentation, replacing GitBook

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha-docs#49]
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

This allows reviewer to see what the site actually changes like without having to pull the changes locally.

MkDocs: https://www.mkdocs.org/

**Comment by frjo** [comment]
Hade a exacellent chat with @theskumar and he have really good experience with MkDocs. I think we should move from GitBook to MkDocs soon.

The current docs are already in markdown so should not be too much work to move them into a MkDocs system.

**Comment by fourthletter** [comment]
Thank you SO much for pushing this forward 💯
