### ISSUE TITLE
Where should this page go?

### ISSUE THREAD

**Issue by maxpearl** [HyphaApp/hypha-docs#5]
@frjo - should [this page](https://github.com/HyphaApp/meta/blob/main/Maintenance.md/QuarterlyMilestoneRebase.md) be in the docs at all? It seems very dev focused. Let us know.

**Comment by frjo** [comment]
@maxpearl No, this is dev documentation.

**Comment by maxpearl** [comment]
OK, I'll delete it.

**Comment by emlini** [comment]
@maxpearl can this issue be closed?
