### ISSUE TITLE
Use a framework/guideline for technical documentation.

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha-docs#53]
The guideline and approach for organizing and to cover in the documentation:  

https://diataxis.fr/

**Comment by frjo** [comment]
@fourthletter We have discussed this guideline for documentation before. I think everyone agrees it is really good.

Can we make an official decision that this is how we organise our documentation?

**Comment by fourthletter** [comment]
> @fourthletter We have discussed this guideline for documentation before. I think everyone agrees it is really good.
> 
> Can we make an official decision that this is how we organise our documentation?

Feel free to reorganize the documentation and I will follow the framework.

**Comment by aurum-linh** [comment]
Just read through all the articles on the website — looks great! It’s very similar to the methodology I developed in my first few weeks — though Diataxis is more comprehensive than my google doc :) https://docs.google.com/document/d/11X68znIX_QqpRvaccrOH0y4Ccl_yAhKy8GQBqfTxPc0/edit?usp=sharing 

Some things that came up in our last meeting were a few questions: what does making this “our official documentation approach” mean? And how do we hold ourselves to that standard moving forward?

Either way, I plan to introduce our methodology for documentation writing in the introduction section of our set of docs.
