### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha-docs#56]
Many files in the documentation are now duplicated, they exist in two places.

Can you clean that up so I know which one to edit?

**Comment by fourthletter** [comment]
Do you know the markdown code for nesting file folders like this one https://github.com/HyphaApp/hypha-docs/tree/main/docs/developers ? I'm currently only able to organize single files, but not folders.

I could delete the duplicate.

~~~~
nav:
  - Home: index.md
  - 'Getting Started':
      - 'Configuration':
        - configurationoptions.md
        - base.py.md
        - dev.py.md
        - example.py.md
        - local.py.md
        - production.py.md
      - 'Deploying':
        - docker.md
        - heroku.md
        - standalone.md
  - 'User Guide':
      - selectworkflow.md
      - setupfundlabround.md
  - 'Developer Guide': 
      - createusers.md
      - localdevdocker.md
      - localdevscratch.md
  - 'Contributing':
      - codeofconduct.md
      - contributetodocumentation.md
      - implementationdetails.md
      - submittingchanges.md
      - testing.md
      - localization.md
  - Glossary: glossary.md
~~~~

**Comment by frjo** [comment]
Not sure what you are trying to do.

The menu is ment to auto populate. I suggest you set it back the the original value.

~~~~
nav:
  - Home: index.md
  - ...
  - Glossary: glossary.md
~~~~

The three dots "..." will automatically fill in everything.

Then you just put files in to directories as needed as normal and it just works.

**Comment by fourthletter** [comment]
OK, I deleted the duplicate files.
