### ISSUE TITLE
Quick Start page

### ISSUE THREAD

**Issue by emlini** [HyphaApp/hypha-docs#9]
I'm thinking "**What is**" and "**Quick Start**" pages would be nice for folks new to Hypha. (see example [What Is](https://docs.gitbook.com) and [Quick Start](https://docs.gitbook.com) pages for Gitbook)

**QUESTIONS:**

1. There is an "[Initial page](https://app.gitbook.com/@hypha/s/meta/)" that could serve as the basis for the "What Is" page, but it could use some editing/polishing.  @danblah, okay if I make some proposed changes to the page?
2. Do folks think a "Quick Start" page would be useful?  What priority level would this be (relative to, say, improving existing user documentation or creating non-existent documentation)?

**Comment by maxpearl** [comment]
I do think a "Quick Start" page is useful. And I'd guess it would actually be a nice start to the user documentation - so you might even start with it, and then that will possibly support the more in-depth docs?

**Comment by frjo** [comment]
I think a Quick start page is an excellent idea.

**Comment by emlini** [comment]
Page created!  

- [Hypha overview page here](https://github.com/HyphaApp/hypha-docs/blob/main/user/GettingStarted_overview.md)
- [Getting started for Staff page here](https://github.com/HyphaApp/hypha-docs/blob/main/user/GettingStarted_staff.md)
